server:
  port: 8000

spring:
  redis:
    host: 192.168.188.129
    port: 6379
    password: 123456
  session:
    store-type: redis #session存储方式
    timeout: 1800    #session过期时间 单位：秒
  thymeleaf:  #开启thymeleaf模板设置
    cache: false #禁用模板缓存